"""Initial migration

Revision ID: 5c0c0de67873
Revises: 
Create Date: 2025-08-04 08:32:58.817827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0c0de67873'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventName', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('isUsed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index('ix_ticket_eventName', ['eventName'], unique=False)
        batch_op.create_index('ix_ticket_time', ['time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index('ix_ticket_time')
        batch_op.drop_index('ix_ticket_eventName')

    op.drop_table('ticket')
    # ### end Alembic commands ###
